apiVersion: "v1"
kind: ServiceAccount
metadata:
  name: my-sa
  namespace: kubeflow-user-example-com
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::136776963499:role/eks_s3_role"
    serving.kserve.io/s3-endpoint: "s3.amazonaws.com" 
    serving.kserve.io/s3-usehttps: "1" 
    serving.kserve.io/s3-region: "eu-west-3"
    serving.kserve.io/s3-useanoncredential: "false" 
