apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "xgboostsrv"
  namespace: kubeflow-user-example-com
spec:
  predictor:
      serviceAccountName: my-sa
      xgboost:  
          storageUri: "s3://fycmodelsprod/new"
